var GAME_LEVELS = [
    ["                                                                            ",
   "  x                                                                            x",
   "  x                                o                                           x",
   "  x            xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                   x",
   "  x         xxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxx                                 x",
   "  x  k   xxxxxxxxx                      xxxxxxxx                               x",
   "  x    xxxxxxxxx                           xxxxxxxxx                           x",
   "  xxxxxxxxxxxx                                 xxxxx!!!!!xx                    x",
   "  xxxxxxxxxx           o                          xxxxvxxxxxx                  x",
   "  xxxxxxxx                                                 xxxx                x",
   "  x                                                                            x",
   "  x                                                                            x",
   "  x                                                                       p    x",
   "  x                                                                            x",
   "  x               xxx     xxx                                           xxxxxxxx",
   "  x            xxxxxx!!!!!xxxxxx    e   oo                           xxxxxxxxxxx",
   "  x@        xxxxxxxxx!!!!!xxxxxxxxx           xxxx               xxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["                                           ",
   "                                           ",
   "  x @                                      ",
   "  xxxxx                                    ",
   "      x     xxxxxx                         ",
   "      x                                xx  ",
   "      x                                xx  ",
   "      x             xxxxx              xx  ",
   "      x                       e        xx  ",
   "      xxxxxxxx       o     xx     xx   xx  ",
   "      x                     xxxxxxx    xx  ",
   "      x          xxxxx                 xx  ",
   "      x                                xx  ",
   "      x                                xx  ",
   "      x        ||         x            xx  ",
   "      x!!!!!!!!!!!!!!!!!!!x         xxxxx  ",
   "      xxxxxxxxxxxxxxxxxxxxx      xxxx  xx  ",
   "      x                                xx  ",
   "      xxx         o                    xx  ",
   "      x                                xx  ",
   "      x         xxxxx       xxx     xxxxx  ",
   "      x |                        o     xx  ",
   "      xxx                       e      xx  ",
   "      x       xx  = xxx    x           xx  ",
   "      x       xxxxxxxxx    xxxxxxxxxxxxxx  ",
   "      xxxxxx  xxx                      xx  ",
   "      x         x                      xx  ",
   "      x  =   o       xxx         x!!!!xx   ",
   "      xxxx   xxxx                xxxxxxxx  ",
   "      xx      x    e    o              xx  ",
   "      xx!!!!!!x            x           xx  ",
   "      xx!!!!!!xxxxxxxxxxxxxx           xx  ",
   "  x   xx!!!!!!xxxxxxxxxxxxxxxxxxx      xx  ",
   "  x   xx!!!!!!xxxxxxxxxxxxxx       k   xx  ",
   "  x   xx!!!!!!xxxxxxxxxxxxxx           xx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "],  
  ["                                                                                               ",
   "                                                                                               ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   " xxxxxxxxxxxx!xxxxxxxxxxxxx!!xxxxxxxxxxxx!!!!!x!x!!!!!!!!xxxxx!xxxxxxxxxxxxxx!xxx!xxxxxxxxxxxxx",
   "            x!x    x!x    x!!x          x!!!!!x!x!!!!!!!!xxxxx!x            x!x x!x        o xx",
   "            x!x    x!x    x!!x          x!!v!!xvxvvvxxxxxx   x!x            x!x x!x          xx",
   "            x!x    x!x    xvvx          xvvxxxxxxxxxx        xvx            xvx xvx         xxx",
   "            x!x    xvx    x  x                                                               xx",
   "            x!x           x  x                                                               xx",
   "            xvx           x  x                                                            xxxxx",
   "                                                     xxxxx                                   xx",
   "                                              o                                           o  xx",
   "                                                                                             xx",
   "                                            xxx                                         xxxxxxx",
   "                                                       o   e xxx   xxx     xxx   xxx         xx",
   "                            o        xxx         xxx         xxx          xxxx   xxxx        xx",
   "                                    xxxx               xx    xxx     e   xxxxx k xxxxx   p   xx",
   "                         xxxxxx    xxxxx                     xxx        xxxxxx   xxxxxx      xx",
   " @                xxxxx  xxxxxx  xxxxxxx               e     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "           xxxxx  xxxxx  xxxxxx  xxxxxxx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"] 
   
   
 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
